/* Generated by Pyrex 0.9.3 on Mon Apr 04 20:26:06 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "C Speedups for commonly-used operations";

/* Declarations from _speedups */

staticforward PyTypeObject __pyx_type_9_speedups__ExtremeType;

struct __pyx_obj_9_speedups__ExtremeType {
  PyObject_HEAD
  int _cmpr;
  PyObject *_rep;
};

staticforward PyTypeObject __pyx_type_9_speedups_ExprCache;

struct __pyx_obj_9_speedups_ExprCache {
  PyObject_HEAD
  PyObject *cache;
  PyObject *argtuple;
  PyObject *expr_defs;
};

staticforward PyTypeObject __pyx_type_9_speedups_BaseDispatcher;

struct __pyx_obj_9_speedups_BaseDispatcher {
  PyObject_HEAD
};

static PyTypeObject *__pyx_ptype_9_speedups__ExtremeType = 0;
static PyTypeObject *__pyx_ptype_9_speedups_ExprCache = 0;
static PyTypeObject *__pyx_ptype_9_speedups_BaseDispatcher = 0;
static PyObject *__pyx_v_9_speedups_NoApplicableMethods;
static PyObject *__pyx_v_9_speedups_DispatchError;
static PyObject *__pyx_v_9_speedups__NF;

/* Implementation of _speedups */

static char (__pyx_k1[]) = "dispatch.interfaces";

static PyObject *__pyx_n___all__;
static PyObject *__pyx_n_Max;
static PyObject *__pyx_n_Min;
static PyObject *__pyx_n_concatenate_ranges;
static PyObject *__pyx_n_dispatch_by_inequalities;
static PyObject *__pyx_n_NoApplicableMethods;
static PyObject *__pyx_n_DispatchError;

static PyObject *__pyx_k1p;

static int __pyx_f_9_speedups_12_ExtremeType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9_speedups_12_ExtremeType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cmpr = 0;
  PyObject *__pyx_v_rep = 0;
  int __pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"cmpr","rep",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_cmpr, &__pyx_v_rep)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_cmpr);
  Py_INCREF(__pyx_v_rep);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":130 */
  __pyx_1 = PyInt_AsLong(__pyx_v_cmpr); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_cmpr = __pyx_1;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":131 */
  Py_INCREF(__pyx_v_rep);
  Py_DECREF(((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_rep);
  ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_rep = __pyx_v_rep;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_speedups._ExtremeType.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_cmpr);
  Py_DECREF(__pyx_v_rep);
  return __pyx_r;
}

static PyObject *__pyx_n_object;
static PyObject *__pyx_n___hash__;

static long __pyx_f_9_speedups_12_ExtremeType___hash__(PyObject *__pyx_v_self); /*proto*/
static long __pyx_f_9_speedups_12_ExtremeType___hash__(PyObject *__pyx_v_self) {
  long __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":134 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n___hash__); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_self);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_4;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_speedups._ExtremeType.__hash__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_9_speedups_12_ExtremeType___cmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_other); /*proto*/
static int __pyx_f_9_speedups_12_ExtremeType___cmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_other) {
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":137 */
  __pyx_2 = PyObject_Type(__pyx_v_other); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_3 = PyObject_Type(__pyx_v_self); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_1 = __pyx_2 == __pyx_3;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_1) {
    __pyx_1 = (((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_other)->_cmpr == ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_cmpr);
  }
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":138 */
    __pyx_r = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":139 */
  __pyx_r = ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_cmpr;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_speedups._ExtremeType.__cmp__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_9_speedups_12_ExtremeType___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9_speedups_12_ExtremeType___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":142 */
  Py_INCREF(((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_rep);
  __pyx_r = ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_rep;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_speedups._ExtremeType.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9_speedups_12_ExtremeType___richcmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_other, int __pyx_v_op); /*proto*/
static PyObject *__pyx_f_9_speedups_12_ExtremeType___richcmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_other, int __pyx_v_op) {
  PyObject *__pyx_v_cmp;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  __pyx_v_cmp = Py_None; Py_INCREF(__pyx_v_cmp);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_self), __pyx_ptype_9_speedups__ExtremeType, 1, "self")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":145 */
  __pyx_2 = PyObject_Type(__pyx_v_other); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_3 = PyObject_Type(__pyx_v_self); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_1 = __pyx_2 == __pyx_3;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_1) {
    __pyx_1 = (((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_other)->_cmpr == ((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_cmpr);
  }
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":146 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
    Py_DECREF(__pyx_v_cmp);
    __pyx_v_cmp = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":148 */
    __pyx_3 = PyInt_FromLong(((struct __pyx_obj_9_speedups__ExtremeType *)__pyx_v_self)->_cmpr); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
    Py_DECREF(__pyx_v_cmp);
    __pyx_v_cmp = __pyx_3;
    __pyx_3 = 0;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":149 */
  __pyx_1 = (__pyx_v_op == 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":150 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_1 = __pyx_1 < 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_op == 1);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":152 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_1 = __pyx_1 <= 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_op == 2);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":154 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
    __pyx_1 = __pyx_1 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_op == 3);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":156 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
    __pyx_1 = __pyx_1 != 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_op == 4);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":158 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
    __pyx_1 = __pyx_1 > 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_op == 5);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":160 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_cmp, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
    __pyx_1 = __pyx_1 >= 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_speedups._ExtremeType.__richcmp__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cmp);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_n_keys;
static PyObject *__pyx_n_sort;
static PyObject *__pyx_n_append;

static PyObject *__pyx_f_9_speedups_concatenate_ranges(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9_speedups_concatenate_ranges(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_range_map = 0;
  PyObject *__pyx_v_ranges;
  PyObject *__pyx_v_output;
  PyObject *__pyx_v_last;
  PyObject *__pyx_v_l;
  PyObject *__pyx_v_h;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"range_map",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_range_map)) return 0;
  Py_INCREF(__pyx_v_range_map);
  __pyx_v_ranges = Py_None; Py_INCREF(__pyx_v_ranges);
  __pyx_v_output = Py_None; Py_INCREF(__pyx_v_output);
  __pyx_v_last = Py_None; Py_INCREF(__pyx_v_last);
  __pyx_v_l = Py_None; Py_INCREF(__pyx_v_l);
  __pyx_v_h = Py_None; Py_INCREF(__pyx_v_h);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":166 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_range_map, __pyx_n_keys); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_ranges);
  __pyx_v_ranges = __pyx_3;
  __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":166 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_ranges, __pyx_n_sort); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":167 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  Py_DECREF(__pyx_v_output);
  __pyx_v_output = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":168 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Min); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
  Py_DECREF(__pyx_v_last);
  __pyx_v_last = __pyx_2;
  __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":169 */
  __pyx_3 = PyObject_GetIter(__pyx_v_ranges); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  for (;;) {
    __pyx_L2:;
    __pyx_1 = PyIter_Next(__pyx_3);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
      break;
    }
    __pyx_2 = __Pyx_UnpackItem(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_DECREF(__pyx_v_l);
    __pyx_v_l = __pyx_2;
    __pyx_2 = 0;
    __pyx_4 = __Pyx_UnpackItem(__pyx_1, 1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_DECREF(__pyx_v_h);
    __pyx_v_h = __pyx_4;
    __pyx_4 = 0;
    if (__Pyx_EndUnpack(__pyx_1, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":170 */
    if (PyObject_Cmp(__pyx_v_l, __pyx_v_last, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
    __pyx_5 = __pyx_5 < 0;
    if (!__pyx_5) {
      if (PyObject_Cmp(__pyx_v_l, __pyx_v_h, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
      __pyx_5 = __pyx_5 == 0;
    }
    if (__pyx_5) {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":171 */
      goto __pyx_L2;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":172 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_output, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    Py_INCREF(__pyx_v_l);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_l);
    Py_INCREF(__pyx_v_h);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_h);
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":173 */
    Py_INCREF(__pyx_v_h);
    Py_DECREF(__pyx_v_last);
    __pyx_v_last = __pyx_v_h;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":174 */
  Py_INCREF(__pyx_v_output);
  __pyx_r = __pyx_v_output;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_speedups.concatenate_ranges");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ranges);
  Py_DECREF(__pyx_v_output);
  Py_DECREF(__pyx_v_last);
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_h);
  Py_DECREF(__pyx_v_range_map);
  return __pyx_r;
}

static PyObject *__pyx_f_9_speedups_dispatch_by_inequalities(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9_speedups_dispatch_by_inequalities(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_table = 0;
  PyObject *__pyx_v_ob = 0;
  int __pyx_v_lo;
  int __pyx_v_hi;
  int __pyx_v_mid;
  void (*__pyx_v_tmp);
  PyObject *__pyx_v_key;
  PyObject *__pyx_v_ranges;
  PyObject *__pyx_v_t;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"table","ob",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_table, &__pyx_v_ob)) return 0;
  Py_INCREF(__pyx_v_table);
  Py_INCREF(__pyx_v_ob);
  __pyx_v_key = Py_None; Py_INCREF(__pyx_v_key);
  __pyx_v_ranges = Py_None; Py_INCREF(__pyx_v_ranges);
  __pyx_v_t = Py_None; Py_INCREF(__pyx_v_t);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":182 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_INCREF(__pyx_v_ob);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_ob);
  Py_INCREF(__pyx_v_ob);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_ob);
  Py_DECREF(__pyx_v_key);
  __pyx_v_key = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":183 */
  __pyx_v_tmp = PyDict_GetItem(__pyx_v_table,__pyx_v_key);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":184 */
  __pyx_2 = (__pyx_v_tmp != 0);
  if (__pyx_2) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":185 */
    __pyx_1 = (PyObject *)__pyx_v_tmp;
    Py_INCREF(__pyx_1);
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":187 */
    __pyx_v_tmp = PyDict_GetItem(__pyx_v_table,Py_None);

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":188 */
    __pyx_2 = (__pyx_v_tmp != 0);
    if (__pyx_2) {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":189 */
      __pyx_1 = (PyObject *)__pyx_v_tmp;
      Py_INCREF(__pyx_1);
      Py_DECREF(__pyx_v_ranges);
      __pyx_v_ranges = __pyx_1;
      __pyx_1 = 0;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":191 */
      __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_concatenate_ranges); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
      Py_INCREF(__pyx_v_table);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_table);
      __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (PyObject_SetItem(__pyx_v_table, Py_None, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
      Py_INCREF(__pyx_4);
      Py_DECREF(__pyx_v_ranges);
      __pyx_v_ranges = __pyx_4;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    __pyx_L3:;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":193 */
    __pyx_v_lo = 0;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":194 */
    __pyx_2 = PyObject_Length(__pyx_v_ranges); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    __pyx_v_hi = __pyx_2;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":195 */
    while (1) {
      __pyx_L4:;
      __pyx_2 = (__pyx_v_lo < __pyx_v_hi);
      if (!__pyx_2) break;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":196 */
      __pyx_v_mid = ((__pyx_v_lo + __pyx_v_hi) / 2);

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":197 */
      __pyx_1 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_ranges),__pyx_v_mid);
      Py_INCREF(__pyx_1);
      Py_DECREF(__pyx_v_t);
      __pyx_v_t = __pyx_1;
      __pyx_1 = 0;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":198 */
      __pyx_3 = (PyObject *)PyTuple_GET_ITEM(((PyTupleObject (*))__pyx_v_t),0);
      Py_INCREF(__pyx_3);
      if (PyObject_Cmp(__pyx_v_ob, __pyx_3, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_2 = __pyx_2 < 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (__pyx_2) {

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":199 */
        __pyx_v_hi = __pyx_v_mid;
        goto __pyx_L6;
      }
      __pyx_4 = (PyObject *)PyTuple_GET_ITEM(((PyTupleObject (*))__pyx_v_t),1);
      Py_INCREF(__pyx_4);
      if (PyObject_Cmp(__pyx_v_ob, __pyx_4, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_2 = __pyx_2 > 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      if (__pyx_2) {

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":201 */
        __pyx_v_lo = (__pyx_v_mid + 1);
        goto __pyx_L6;
      }
      /*else*/ {

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":203 */
        __pyx_1 = PyObject_GetItem(__pyx_v_table, __pyx_v_t); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
        __pyx_r = __pyx_1;
        __pyx_1 = 0;
        goto __pyx_L0;
      }
      __pyx_L6:;
    }
    __pyx_L5:;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_speedups.dispatch_by_inequalities");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_ranges);
  Py_DECREF(__pyx_v_t);
  Py_DECREF(__pyx_v_table);
  Py_DECREF(__pyx_v_ob);
  return __pyx_r;
}

static int __pyx_f_9_speedups_9ExprCache___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9_speedups_9ExprCache___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_argtuple = 0;
  PyObject *__pyx_v_expr_defs = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"argtuple","expr_defs",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_argtuple, &__pyx_v_expr_defs)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_argtuple);
  Py_INCREF(__pyx_v_expr_defs);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":211 */
  Py_INCREF(__pyx_v_argtuple);
  Py_DECREF(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->argtuple);
  ((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->argtuple = __pyx_v_argtuple;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":212 */
  Py_INCREF(__pyx_v_expr_defs);
  Py_DECREF(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->expr_defs);
  ((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->expr_defs = __pyx_v_expr_defs;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":213 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->cache);
  ((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->cache = __pyx_1;
  __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_speedups.ExprCache.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_argtuple);
  Py_DECREF(__pyx_v_expr_defs);
  return __pyx_r;
}

static PyObject *__pyx_n___getitem__;
static PyObject *__pyx_n_IndexError;
static PyObject *__pyx_n_KeyError;
static PyObject *__pyx_n_map;

static PyObject *__pyx_f_9_speedups_9ExprCache___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_item); /*proto*/
static PyObject *__pyx_f_9_speedups_9ExprCache___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_item) {
  PyObject *__pyx_v_f;
  PyObject *__pyx_v_args;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_item);
  __pyx_v_f = Py_None; Py_INCREF(__pyx_v_f);
  __pyx_v_args = Py_None; Py_INCREF(__pyx_v_args);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":216 */
  __pyx_1 = PyInt_FromLong((-1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_item, __pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  __pyx_2 = __pyx_2 == 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":217 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n___getitem__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":218 */
  /*try:*/ {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":219 */
    __pyx_1 = PyObject_GetItem(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->argtuple, __pyx_v_item); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L3;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
  }
  goto __pyx_L4;
  __pyx_L3:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":220 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_IndexError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  __pyx_2 = PyErr_ExceptionMatches(__pyx_1);
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {
    __Pyx_AddTraceback("_speedups.__getitem__");
    __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":221 */
    goto __pyx_L4;
  }
  goto __pyx_L1;
  __pyx_L4:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":222 */
  /*try:*/ {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":223 */
    __pyx_1 = PyObject_GetItem(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->cache, __pyx_v_item); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L5;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
  }
  goto __pyx_L6;
  __pyx_L5:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":224 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_KeyError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  __pyx_2 = PyErr_ExceptionMatches(__pyx_1);
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {
    __Pyx_AddTraceback("_speedups.__getitem__");
    __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":225 */
    goto __pyx_L6;
  }
  goto __pyx_L1;
  __pyx_L6:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":227 */
  __pyx_1 = PyObject_GetItem(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->expr_defs, __pyx_v_item); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  __pyx_3 = __Pyx_UnpackItem(__pyx_1, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_v_f);
  __pyx_v_f = __pyx_3;
  __pyx_3 = 0;
  __pyx_4 = __Pyx_UnpackItem(__pyx_1, 1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_v_args);
  __pyx_v_args = __pyx_4;
  __pyx_4 = 0;
  if (__Pyx_EndUnpack(__pyx_1, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":228 */
  __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_map); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n___getitem__); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  Py_INCREF(__pyx_v_args);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_args);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PySequence_Tuple(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_v_f, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_INCREF(__pyx_1);
  Py_DECREF(__pyx_v_f);
  __pyx_v_f = __pyx_1;
  if (PyObject_SetItem(((struct __pyx_obj_9_speedups_ExprCache *)__pyx_v_self)->cache, __pyx_v_item, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":229 */
  Py_INCREF(__pyx_v_f);
  __pyx_r = __pyx_v_f;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_speedups.ExprCache.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_f);
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_item);
  return __pyx_r;
}

static PyObject *__pyx_n__dispatcher;
static PyObject *__pyx_n__startNode;
static PyObject *__pyx_n__acquire;
static PyObject *__pyx_n__release;
static PyObject *__pyx_n_expr_defs;

static PyObject *__pyx_f_9_speedups_14BaseDispatcher___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_argtuple); /*proto*/
static PyObject *__pyx_f_9_speedups_14BaseDispatcher___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_argtuple) {
  int __pyx_v_expr;
  int __pyx_v_argct;
  PyObject *__pyx_v_node;
  PyObject *__pyx_v_factory;
  PyObject *__pyx_v_func;
  PyObject *__pyx_v_cache;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  int __pyx_8;
  int __pyx_9;
  int __pyx_10;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_argtuple);
  __pyx_v_node = Py_None; Py_INCREF(__pyx_v_node);
  __pyx_v_factory = Py_None; Py_INCREF(__pyx_v_factory);
  __pyx_v_func = Py_None; Py_INCREF(__pyx_v_func);
  __pyx_v_cache = Py_None; Py_INCREF(__pyx_v_cache);

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":251 */
  if (!PyTuple_Check(__pyx_v_argtuple)) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
  }

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":254 */
  __pyx_1 = PyObject_Length(__pyx_v_argtuple); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
  __pyx_v_argct = __pyx_1;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":255 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n__dispatcher); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
  __pyx_1 = PyObject_IsTrue(__pyx_2); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
  if (!__pyx_1) {
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_v_self, __pyx_n__startNode); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_1 = PyObject_IsTrue(__pyx_2); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
    if (!__pyx_1) {
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = __pyx_v_9_speedups__NF;
      Py_INCREF(__pyx_2);
    }
  }
  Py_DECREF(__pyx_v_node);
  __pyx_v_node = __pyx_2;
  __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":257 */
  __pyx_3 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),1);
  Py_INCREF(__pyx_3);
  Py_DECREF(__pyx_v_factory);
  __pyx_v_factory = __pyx_3;
  __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":258 */
  __pyx_4 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),2);
  Py_INCREF(__pyx_4);
  Py_DECREF(__pyx_v_func);
  __pyx_v_func = __pyx_4;
  __pyx_4 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":260 */
  while (1) {
    __pyx_L2:;
    __pyx_1 = __pyx_v_factory != Py_None;
    if (!__pyx_1) break;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":262 */
    __pyx_1 = __pyx_v_func == Py_None;
    if (__pyx_1) {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":263 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n__acquire); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
      __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":264 */
      /*try:*/ {

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":265 */
        __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 265; goto __pyx_L8;}
        __pyx_3 = PyObject_GetItem(__pyx_v_node, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 265; goto __pyx_L8;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        __pyx_1 = __pyx_3 == Py_None;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        if (__pyx_1) {

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":266 */
          __pyx_4 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),3);
          Py_INCREF(__pyx_4);
          __pyx_2 = PySequence_Tuple(__pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L8;}
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          __pyx_3 = PyObject_CallObject(__pyx_v_factory, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L8;}
          Py_DECREF(__pyx_2); __pyx_2 = 0;
          __pyx_4 = PyInt_FromLong(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L8;}
          if (PyObject_SetItem(__pyx_v_node, __pyx_4, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L8;}
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          Py_INCREF(__pyx_3);
          Py_DECREF(__pyx_v_func);
          __pyx_v_func = __pyx_3;
          Py_DECREF(__pyx_3); __pyx_3 = 0;
          goto __pyx_L10;
        }
        __pyx_L10:;
      }
      /*finally:*/ {
        int __pyx_why;
        __pyx_why = 0; goto __pyx_L9;
        __pyx_L5: __pyx_why = 1; goto __pyx_L9;
        __pyx_L6: __pyx_why = 2; goto __pyx_L9;
        __pyx_L7: __pyx_why = 3; goto __pyx_L9;
        __pyx_L8: {
          __pyx_why = 4;
          Py_XDECREF(__pyx_2); __pyx_2 = 0;
          Py_XDECREF(__pyx_4); __pyx_4 = 0;
          Py_XDECREF(__pyx_3); __pyx_3 = 0;
          PyErr_Fetch(&__pyx_2, &__pyx_4, &__pyx_3);
          __pyx_1 = __pyx_lineno;
          goto __pyx_L9;
        }
        __pyx_L9:;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":270 */
        __pyx_5 = PyObject_GetAttr(__pyx_v_self, __pyx_n__release); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
        __pyx_6 = PyTuple_New(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
        __pyx_7 = PyObject_CallObject(__pyx_5, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        switch (__pyx_why) {
          case 1: goto __pyx_L2;
          case 2: goto __pyx_L3;
          case 3: goto __pyx_L0;
          case 4: {
            PyErr_Restore(__pyx_2, __pyx_4, __pyx_3);
            __pyx_lineno = __pyx_1;
            __pyx_2 = 0;
            __pyx_4 = 0;
            __pyx_3 = 0;
            goto __pyx_L1;
          }
        }
      }
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":272 */
    __pyx_5 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),0);
    Py_INCREF(__pyx_5);
    __pyx_8 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 272; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_expr = __pyx_8;

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":273 */
    __pyx_8 = (__pyx_v_expr < __pyx_v_argct);
    if (__pyx_8) {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":276 */
      __pyx_7 = (PyObject *)PyTuple_GET_ITEM(((PyTupleObject (*))__pyx_v_argtuple),__pyx_v_expr);
      Py_INCREF(__pyx_7);
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_7);
      __pyx_7 = 0;
      __pyx_6 = PyObject_CallObject(__pyx_v_func, __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_8 = PyObject_IsTrue(__pyx_6); if (__pyx_8 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 276; goto __pyx_L1;}
      if (!__pyx_8) {
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        __pyx_6 = __pyx_v_9_speedups__NF;
        Py_INCREF(__pyx_6);
      }
      Py_DECREF(__pyx_v_node);
      __pyx_v_node = __pyx_6;
      __pyx_6 = 0;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":277 */
      __pyx_4 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),1);
      Py_INCREF(__pyx_4);
      Py_DECREF(__pyx_v_factory);
      __pyx_v_factory = __pyx_4;
      __pyx_4 = 0;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":278 */
      __pyx_3 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),2);
      Py_INCREF(__pyx_3);
      Py_DECREF(__pyx_v_func);
      __pyx_v_func = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L11;
    }
    /*else*/ {

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":289 */
      __pyx_5 = PyObject_GetAttr(__pyx_v_self, __pyx_n_expr_defs); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
      __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
      Py_INCREF(__pyx_v_argtuple);
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_v_argtuple);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_5);
      __pyx_5 = 0;
      __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_9_speedups_ExprCache), __pyx_7); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_v_cache);
      __pyx_v_cache = __pyx_2;
      __pyx_2 = 0;

      /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":290 */
      /*try:*/ {

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":291 */
        __pyx_4 = PyInt_FromLong(__pyx_v_expr); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L15;}
        __pyx_3 = PyObject_GetItem(__pyx_v_cache, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L15;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L15;}
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_6 = PyObject_CallObject(__pyx_v_func, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L15;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        __pyx_8 = PyObject_IsTrue(__pyx_6); if (__pyx_8 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L15;}
        if (!__pyx_8) {
          Py_DECREF(__pyx_6); __pyx_6 = 0;
          __pyx_6 = __pyx_v_9_speedups__NF;
          Py_INCREF(__pyx_6);
        }
        Py_DECREF(__pyx_v_node);
        __pyx_v_node = __pyx_6;
        __pyx_6 = 0;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":292 */
        __pyx_7 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),1);
        Py_INCREF(__pyx_7);
        Py_DECREF(__pyx_v_factory);
        __pyx_v_factory = __pyx_7;
        __pyx_7 = 0;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":293 */
        __pyx_2 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),2);
        Py_INCREF(__pyx_2);
        Py_DECREF(__pyx_v_func);
        __pyx_v_func = __pyx_2;
        __pyx_2 = 0;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":294 */
        while (1) {
          __pyx_L17:;
          __pyx_8 = __pyx_v_factory != Py_None;
          if (!__pyx_8) break;

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":295 */
          __pyx_8 = __pyx_v_func == Py_None;
          if (__pyx_8) {

            /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":296 */
            __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n__acquire); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 296; goto __pyx_L15;}
            __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 296; goto __pyx_L15;}
            __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 296; goto __pyx_L15;}
            Py_DECREF(__pyx_4); __pyx_4 = 0;
            Py_DECREF(__pyx_3); __pyx_3 = 0;
            Py_DECREF(__pyx_5); __pyx_5 = 0;

            /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":297 */
            /*try:*/ {

              /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":298 */
              __pyx_6 = PyInt_FromLong(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 298; goto __pyx_L23;}
              __pyx_7 = PyObject_GetItem(__pyx_v_node, __pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 298; goto __pyx_L23;}
              Py_DECREF(__pyx_6); __pyx_6 = 0;
              __pyx_8 = __pyx_7 == Py_None;
              Py_DECREF(__pyx_7); __pyx_7 = 0;
              if (__pyx_8) {

                /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":299 */
                __pyx_2 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),3);
                Py_INCREF(__pyx_2);
                __pyx_4 = PySequence_Tuple(__pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L23;}
                Py_DECREF(__pyx_2); __pyx_2 = 0;
                __pyx_3 = PyObject_CallObject(__pyx_v_factory, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L23;}
                Py_DECREF(__pyx_4); __pyx_4 = 0;
                __pyx_5 = PyInt_FromLong(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L23;}
                if (PyObject_SetItem(__pyx_v_node, __pyx_5, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L23;}
                Py_DECREF(__pyx_5); __pyx_5 = 0;
                Py_INCREF(__pyx_3);
                Py_DECREF(__pyx_v_func);
                __pyx_v_func = __pyx_3;
                Py_DECREF(__pyx_3); __pyx_3 = 0;
                goto __pyx_L25;
              }
              __pyx_L25:;
            }
            /*finally:*/ {
              int __pyx_why;
              __pyx_why = 0; goto __pyx_L24;
              __pyx_L20: __pyx_why = 1; goto __pyx_L24;
              __pyx_L21: __pyx_why = 2; goto __pyx_L24;
              __pyx_L22: __pyx_why = 3; goto __pyx_L24;
              __pyx_L23: {
                __pyx_why = 4;
                Py_XDECREF(__pyx_6); __pyx_6 = 0;
                Py_XDECREF(__pyx_7); __pyx_7 = 0;
                Py_XDECREF(__pyx_2); __pyx_2 = 0;
                Py_XDECREF(__pyx_4); __pyx_4 = 0;
                Py_XDECREF(__pyx_5); __pyx_5 = 0;
                Py_XDECREF(__pyx_3); __pyx_3 = 0;
                PyErr_Fetch(&__pyx_6, &__pyx_7, &__pyx_2);
                __pyx_8 = __pyx_lineno;
                goto __pyx_L24;
              }
              __pyx_L24:;

              /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":303 */
              __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n__release); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L15;}
              __pyx_5 = PyTuple_New(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L15;}
              __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L15;}
              Py_DECREF(__pyx_4); __pyx_4 = 0;
              Py_DECREF(__pyx_5); __pyx_5 = 0;
              Py_DECREF(__pyx_3); __pyx_3 = 0;
              switch (__pyx_why) {
                case 1: goto __pyx_L17;
                case 2: goto __pyx_L18;
                case 3: goto __pyx_L14;
                case 4: {
                  PyErr_Restore(__pyx_6, __pyx_7, __pyx_2);
                  __pyx_lineno = __pyx_8;
                  __pyx_6 = 0;
                  __pyx_7 = 0;
                  __pyx_2 = 0;
                  goto __pyx_L15;
                }
              }
            }
            goto __pyx_L19;
          }
          __pyx_L19:;

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":304 */
          __pyx_4 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),0);
          Py_INCREF(__pyx_4);
          __pyx_9 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L15;}
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          __pyx_v_expr = __pyx_9;

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":305 */
          __pyx_9 = (__pyx_v_expr < __pyx_v_argct);
          if (__pyx_9) {

            /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":308 */
            __pyx_3 = (PyObject *)PyTuple_GET_ITEM(((PyTupleObject (*))__pyx_v_argtuple),__pyx_v_expr);
            Py_INCREF(__pyx_3);
            __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L15;}
            PyTuple_SET_ITEM(__pyx_6, 0, __pyx_3);
            __pyx_3 = 0;
            __pyx_5 = PyObject_CallObject(__pyx_v_func, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L15;}
            Py_DECREF(__pyx_6); __pyx_6 = 0;
            __pyx_9 = PyObject_IsTrue(__pyx_5); if (__pyx_9 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L15;}
            if (!__pyx_9) {
              Py_DECREF(__pyx_5); __pyx_5 = 0;
              __pyx_5 = __pyx_v_9_speedups__NF;
              Py_INCREF(__pyx_5);
            }
            Py_DECREF(__pyx_v_node);
            __pyx_v_node = __pyx_5;
            __pyx_5 = 0;
            goto __pyx_L26;
          }
          /*else*/ {

            /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":310 */
            __pyx_2 = PyInt_FromLong(__pyx_v_expr); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L15;}
            __pyx_4 = PyObject_GetItem(__pyx_v_cache, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L15;}
            Py_DECREF(__pyx_2); __pyx_2 = 0;
            __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L15;}
            PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
            __pyx_4 = 0;
            __pyx_7 = PyObject_CallObject(__pyx_v_func, __pyx_3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L15;}
            Py_DECREF(__pyx_3); __pyx_3 = 0;
            __pyx_9 = PyObject_IsTrue(__pyx_7); if (__pyx_9 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L15;}
            if (!__pyx_9) {
              Py_DECREF(__pyx_7); __pyx_7 = 0;
              __pyx_7 = __pyx_v_9_speedups__NF;
              Py_INCREF(__pyx_7);
            }
            Py_DECREF(__pyx_v_node);
            __pyx_v_node = __pyx_7;
            __pyx_7 = 0;
          }
          __pyx_L26:;

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":312 */
          __pyx_6 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),1);
          Py_INCREF(__pyx_6);
          Py_DECREF(__pyx_v_factory);
          __pyx_v_factory = __pyx_6;
          __pyx_6 = 0;

          /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":313 */
          __pyx_5 = (PyObject *)PyList_GET_ITEM(((PyListObject (*))__pyx_v_node),2);
          Py_INCREF(__pyx_5);
          Py_DECREF(__pyx_v_func);
          __pyx_v_func = __pyx_5;
          __pyx_5 = 0;
        }
        __pyx_L18:;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":315 */
        goto __pyx_L13;
      }
      /*finally:*/ {
        int __pyx_why;
        __pyx_why = 0; goto __pyx_L16;
        __pyx_L12: __pyx_why = 1; goto __pyx_L16;
        __pyx_L13: __pyx_why = 2; goto __pyx_L16;
        __pyx_L14: __pyx_why = 3; goto __pyx_L16;
        __pyx_L15: {
          __pyx_why = 4;
          Py_XDECREF(__pyx_2); __pyx_2 = 0;
          Py_XDECREF(__pyx_4); __pyx_4 = 0;
          Py_XDECREF(__pyx_3); __pyx_3 = 0;
          Py_XDECREF(__pyx_7); __pyx_7 = 0;
          Py_XDECREF(__pyx_6); __pyx_6 = 0;
          Py_XDECREF(__pyx_5); __pyx_5 = 0;
          PyErr_Fetch(&__pyx_2, &__pyx_4, &__pyx_3);
          __pyx_9 = __pyx_lineno;
          goto __pyx_L16;
        }
        __pyx_L16:;

        /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":318 */
        Py_INCREF(Py_None);
        Py_DECREF(__pyx_v_cache);
        __pyx_v_cache = Py_None;
        switch (__pyx_why) {
          case 1: goto __pyx_L2;
          case 2: goto __pyx_L3;
          case 3: goto __pyx_L0;
          case 4: {
            PyErr_Restore(__pyx_2, __pyx_4, __pyx_3);
            __pyx_lineno = __pyx_9;
            __pyx_2 = 0;
            __pyx_4 = 0;
            __pyx_3 = 0;
            goto __pyx_L1;
          }
        }
      }
    }
    __pyx_L11:;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":320 */
  __pyx_10 = PyInstance_Check(__pyx_v_func);
  if (__pyx_10) {
    __pyx_10 = PyObject_IsInstance(__pyx_v_func,__pyx_v_9_speedups_DispatchError);
  }
  if (__pyx_10) {

    /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":321 */
    __pyx_7 = PySequence_Tuple(__pyx_v_argtuple); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 321; goto __pyx_L1;}
    __pyx_6 = PyObject_CallObject(__pyx_v_func, __pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 321; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    goto __pyx_L27;
  }
  __pyx_L27:;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":323 */
  Py_INCREF(__pyx_v_func);
  __pyx_r = __pyx_v_func;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("_speedups.BaseDispatcher.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_node);
  Py_DECREF(__pyx_v_factory);
  Py_DECREF(__pyx_v_func);
  Py_DECREF(__pyx_v_cache);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_argtuple);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_DispatchError, "DispatchError"},
  {&__pyx_n_IndexError, "IndexError"},
  {&__pyx_n_KeyError, "KeyError"},
  {&__pyx_n_Max, "Max"},
  {&__pyx_n_Min, "Min"},
  {&__pyx_n_NoApplicableMethods, "NoApplicableMethods"},
  {&__pyx_n___all__, "__all__"},
  {&__pyx_n___getitem__, "__getitem__"},
  {&__pyx_n___hash__, "__hash__"},
  {&__pyx_n__acquire, "_acquire"},
  {&__pyx_n__dispatcher, "_dispatcher"},
  {&__pyx_n__release, "_release"},
  {&__pyx_n__startNode, "_startNode"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_concatenate_ranges, "concatenate_ranges"},
  {&__pyx_n_dispatch_by_inequalities, "dispatch_by_inequalities"},
  {&__pyx_n_expr_defs, "expr_defs"},
  {&__pyx_n_keys, "keys"},
  {&__pyx_n_map, "map"},
  {&__pyx_n_object, "object"},
  {&__pyx_n_sort, "sort"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_9_speedups__ExtremeType(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_9_speedups__ExtremeType *p = (struct __pyx_obj_9_speedups__ExtremeType *)o;
  p->_rep = Py_None; Py_INCREF(p->_rep);
  return o;
}

static void __pyx_tp_dealloc_9_speedups__ExtremeType(PyObject *o) {
  struct __pyx_obj_9_speedups__ExtremeType *p = (struct __pyx_obj_9_speedups__ExtremeType *)o;
  Py_XDECREF(p->_rep);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9_speedups__ExtremeType(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9_speedups__ExtremeType *p = (struct __pyx_obj_9_speedups__ExtremeType *)o;
  if (p->_rep) {
    e = (*v)(p->_rep, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_9_speedups__ExtremeType(PyObject *o) {
  struct __pyx_obj_9_speedups__ExtremeType *p = (struct __pyx_obj_9_speedups__ExtremeType *)o;
  Py_XDECREF(p->_rep);
  p->_rep = Py_None; Py_INCREF(p->_rep);
  return 0;
}

static struct PyMethodDef __pyx_methods_9_speedups__ExtremeType[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number__ExtremeType = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence__ExtremeType = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping__ExtremeType = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer__ExtremeType = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_9_speedups__ExtremeType = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_speedups._ExtremeType", /*tp_name*/
  sizeof(struct __pyx_obj_9_speedups__ExtremeType), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9_speedups__ExtremeType, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  __pyx_f_9_speedups_12_ExtremeType___cmp__, /*tp_compare*/
  __pyx_f_9_speedups_12_ExtremeType___repr__, /*tp_repr*/
  &__pyx_tp_as_number__ExtremeType, /*tp_as_number*/
  &__pyx_tp_as_sequence__ExtremeType, /*tp_as_sequence*/
  &__pyx_tp_as_mapping__ExtremeType, /*tp_as_mapping*/
  __pyx_f_9_speedups_12_ExtremeType___hash__, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer__ExtremeType, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9_speedups__ExtremeType, /*tp_traverse*/
  __pyx_tp_clear_9_speedups__ExtremeType, /*tp_clear*/
  __pyx_f_9_speedups_12_ExtremeType___richcmp__, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9_speedups__ExtremeType, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_9_speedups_12_ExtremeType___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9_speedups__ExtremeType, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9_speedups_ExprCache(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_9_speedups_ExprCache *p = (struct __pyx_obj_9_speedups_ExprCache *)o;
  p->cache = Py_None; Py_INCREF(p->cache);
  p->argtuple = Py_None; Py_INCREF(p->argtuple);
  p->expr_defs = Py_None; Py_INCREF(p->expr_defs);
  return o;
}

static void __pyx_tp_dealloc_9_speedups_ExprCache(PyObject *o) {
  struct __pyx_obj_9_speedups_ExprCache *p = (struct __pyx_obj_9_speedups_ExprCache *)o;
  Py_XDECREF(p->cache);
  Py_XDECREF(p->argtuple);
  Py_XDECREF(p->expr_defs);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9_speedups_ExprCache(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9_speedups_ExprCache *p = (struct __pyx_obj_9_speedups_ExprCache *)o;
  if (p->cache) {
    e = (*v)(p->cache, a); if (e) return e;
  }
  if (p->argtuple) {
    e = (*v)(p->argtuple, a); if (e) return e;
  }
  if (p->expr_defs) {
    e = (*v)(p->expr_defs, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_9_speedups_ExprCache(PyObject *o) {
  struct __pyx_obj_9_speedups_ExprCache *p = (struct __pyx_obj_9_speedups_ExprCache *)o;
  Py_XDECREF(p->cache);
  p->cache = Py_None; Py_INCREF(p->cache);
  Py_XDECREF(p->argtuple);
  p->argtuple = Py_None; Py_INCREF(p->argtuple);
  Py_XDECREF(p->expr_defs);
  p->expr_defs = Py_None; Py_INCREF(p->expr_defs);
  return 0;
}
static PyObject *__pyx_sq_item_9_speedups_ExprCache(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static struct PyMethodDef __pyx_methods_9_speedups_ExprCache[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ExprCache = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_ExprCache = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_9_speedups_ExprCache, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ExprCache = {
  0, /*mp_length*/
  __pyx_f_9_speedups_9ExprCache___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ExprCache = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_9_speedups_ExprCache = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_speedups.ExprCache", /*tp_name*/
  sizeof(struct __pyx_obj_9_speedups_ExprCache), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9_speedups_ExprCache, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ExprCache, /*tp_as_number*/
  &__pyx_tp_as_sequence_ExprCache, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ExprCache, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ExprCache, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9_speedups_ExprCache, /*tp_traverse*/
  __pyx_tp_clear_9_speedups_ExprCache, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9_speedups_ExprCache, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_9_speedups_9ExprCache___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9_speedups_ExprCache, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9_speedups_BaseDispatcher(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_9_speedups_BaseDispatcher *p = (struct __pyx_obj_9_speedups_BaseDispatcher *)o;
  return o;
}

static void __pyx_tp_dealloc_9_speedups_BaseDispatcher(PyObject *o) {
  struct __pyx_obj_9_speedups_BaseDispatcher *p = (struct __pyx_obj_9_speedups_BaseDispatcher *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9_speedups_BaseDispatcher(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9_speedups_BaseDispatcher *p = (struct __pyx_obj_9_speedups_BaseDispatcher *)o;
  return 0;
}

static int __pyx_tp_clear_9_speedups_BaseDispatcher(PyObject *o) {
  struct __pyx_obj_9_speedups_BaseDispatcher *p = (struct __pyx_obj_9_speedups_BaseDispatcher *)o;
  return 0;
}
static PyObject *__pyx_sq_item_9_speedups_BaseDispatcher(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static struct PyMethodDef __pyx_methods_9_speedups_BaseDispatcher[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BaseDispatcher = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BaseDispatcher = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_9_speedups_BaseDispatcher, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BaseDispatcher = {
  0, /*mp_length*/
  __pyx_f_9_speedups_14BaseDispatcher___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BaseDispatcher = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_9_speedups_BaseDispatcher = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_speedups.BaseDispatcher", /*tp_name*/
  sizeof(struct __pyx_obj_9_speedups_BaseDispatcher), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9_speedups_BaseDispatcher, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BaseDispatcher, /*tp_as_number*/
  &__pyx_tp_as_sequence_BaseDispatcher, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BaseDispatcher, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BaseDispatcher, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9_speedups_BaseDispatcher, /*tp_traverse*/
  __pyx_tp_clear_9_speedups_BaseDispatcher, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9_speedups_BaseDispatcher, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9_speedups_BaseDispatcher, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"concatenate_ranges", (PyCFunction)__pyx_f_9_speedups_concatenate_ranges, METH_VARARGS|METH_KEYWORDS, 0},
  {"dispatch_by_inequalities", (PyCFunction)__pyx_f_9_speedups_dispatch_by_inequalities, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

DL_EXPORT(void) init_speedups(void); /*proto*/
DL_EXPORT(void) init_speedups(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_m = Py_InitModule4("_speedups", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_v_9_speedups_NoApplicableMethods = Py_None; Py_INCREF(__pyx_v_9_speedups_NoApplicableMethods);
  __pyx_v_9_speedups_DispatchError = Py_None; Py_INCREF(__pyx_v_9_speedups_DispatchError);
  __pyx_v_9_speedups__NF = Py_None; Py_INCREF(__pyx_v_9_speedups__NF);
  __pyx_type_9_speedups__ExtremeType.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_9_speedups__ExtremeType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "_ExtremeType", (PyObject *)&__pyx_type_9_speedups__ExtremeType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_ptype_9_speedups__ExtremeType = &__pyx_type_9_speedups__ExtremeType;
  __pyx_type_9_speedups_ExprCache.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_9_speedups_ExprCache) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ExprCache", (PyObject *)&__pyx_type_9_speedups_ExprCache) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  __pyx_ptype_9_speedups_ExprCache = &__pyx_type_9_speedups_ExprCache;
  if (PyType_Ready(&__pyx_type_9_speedups_BaseDispatcher) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 247; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BaseDispatcher", (PyObject *)&__pyx_type_9_speedups_BaseDispatcher) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 247; goto __pyx_L1;}
  __pyx_ptype_9_speedups_BaseDispatcher = &__pyx_type_9_speedups_BaseDispatcher;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":3 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n___all__, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":7 */
  __pyx_1 = PyList_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_INCREF(__pyx_n_NoApplicableMethods);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_NoApplicableMethods);
  Py_INCREF(__pyx_n_DispatchError);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_DispatchError);
  __pyx_2 = __Pyx_Import(__pyx_k1p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_NoApplicableMethods); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_v_9_speedups_NoApplicableMethods);
  __pyx_v_9_speedups_NoApplicableMethods = __pyx_1;
  __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_DispatchError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_v_9_speedups_DispatchError);
  __pyx_v_9_speedups_DispatchError = __pyx_1;
  __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":9 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_INCREF(Py_None);
  PyTuple_SET_ITEM(__pyx_1, 0, Py_None);
  Py_INCREF(Py_None);
  PyTuple_SET_ITEM(__pyx_1, 1, Py_None);
  __pyx_3 = PyList_New(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_3, 0, __pyx_2);
  Py_INCREF(Py_None);
  PyList_SET_ITEM(__pyx_3, 1, Py_None);
  Py_INCREF(__pyx_v_9_speedups_NoApplicableMethods);
  PyList_SET_ITEM(__pyx_3, 2, __pyx_v_9_speedups_NoApplicableMethods);
  PyList_SET_ITEM(__pyx_3, 3, __pyx_1);
  __pyx_2 = 0;
  __pyx_1 = 0;
  Py_DECREF(__pyx_v_9_speedups__NF);
  __pyx_v_9_speedups__NF = __pyx_3;
  __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":162 */
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  Py_INCREF(__pyx_n_Max);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_Max);
  __pyx_2 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_9_speedups__ExtremeType), __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Max, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":163 */
  __pyx_2 = PyInt_FromLong((-1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  Py_INCREF(__pyx_n_Min);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_Min);
  __pyx_2 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_9_speedups__ExtremeType), __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Min, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "C:\cygwin\home\pje\PyProtocols\src/dispatch/_speedups.pyx":249 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_speedups");
}

static char *__pyx_filenames[] = {
  "_speedups.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, int i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, int i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
